  # Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu 16.04'

variables:
- name: imageName
  value: 'quay.io/tcfbank/cloud-custodian:$(build.buildId)'
- group: quay-vars 

steps:
- script: docker build -f Dockerfile -t $(imageName) .
  displayName: 'docker build'

- script: |
    docker login -u $(quayUser) -p $(quayPswd) quay.io
    docker push $(imageName)
  displayName: 'Push to Quay.io'


